
language: cpp
sudo: required
services: ['docker']

branches:
 except:
  - legacy-win32

matrix:
 include:
  - os: linux
    dist: trusty
    compiler: clang
  - os: linux
    dist: trusty
    compiler: gcc
  - os: osx
    compiler: clang

install:
 - ./.travis-install-deps.sh

script:
 - scons CC=$CC CXX=$CXX CXXFLAGS=-DBOOST_NO_CXX11_SCOPED_ENUMS

notifications:
 email: false
 irc:
  channels: ["irc.freenode.net#openboe"]
  use_notice: true
  on_success: change
  on_failure: always
